version: '3.9'

services:

  db:
    container_name: pg_db
    image: postgres:13.3
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  app:
    restart: always
    build:
      context: .
    volumes:
      - .:/fastapi
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - pgadmin

volumes:
  postgres_data: null
